# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = 'ace3d70909787db54b4035b9579376d9'
  config.secret_key = '25bafb5acf8aed9305e4599d99e14ad3'
  config.default_from = 'hnr.berger@gmail.com'

end
