# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = "#{Rails.application.credentials.API_Public_Key}"
  config.secret_key = "#{Rails.application.credentials.API_Secret_Key}"
  config.default_from = 'hnr.berger@gmail.com'

end
